from enum import Enum


class VexStatus(str, Enum):
    NOT_AFFECTED = "NOT_AFFECTED"
    NOT_EXPLOITABLE = "NOT_EXPLOITABLE"
    EXPLOITABLE = "EXPLOITABLE"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"